from __future__ import annotations

import argparse
import json
import logging
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = PROJECT_ROOT / "src"
REVIEW_ROOT = SRC_ROOT / "voicerecognizer" / "evaluation"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(REVIEW_ROOT) not in sys.path:
    sys.path.insert(0, str(REVIEW_ROOT))

from review import ReviewDecision, load_review_decisions, utc_now_iso  # noqa: E402

logger = logging.getLogger(__name__)

DeleteStatus = Literal[
    "would_delete",
    "deleted",
    "missing",
    "skipped_outside_project",
    "skipped_not_wav",
    "error",
]


@dataclass(frozen=True)
class DeleteReviewCandidateResult:
    filepath: str
    resolved_path: str
    label: str
    prediction: str
    confidence: float | None
    decision: str
    status: DeleteStatus
    message: str = ""


def resolve_review_filepath(filepath: str, project_root: Path = PROJECT_ROOT) -> Path:
    path = Path(filepath)
    if not path.is_absolute():
        path = project_root / filepath
    return path.resolve(strict=False)


def _is_inside_project(path: Path, project_root: Path) -> bool:
    try:
        path.relative_to(project_root.resolve(strict=False))
        return True
    except ValueError:
        return False


def _result(
    decision: ReviewDecision,
    resolved_path: Path,
    status: DeleteStatus,
    message: str = "",
) -> DeleteReviewCandidateResult:
    return DeleteReviewCandidateResult(
        filepath=decision.filepath,
        resolved_path=str(resolved_path),
        label=decision.label,
        prediction=decision.prediction,
        confidence=decision.confidence,
        decision=decision.decision,
        status=status,
        message=message,
    )


def delete_review_candidates(
    decisions_path: Path | str,
    *,
    project_root: Path = PROJECT_ROOT,
    execute: bool = False,
    allow_outside_project: bool = False,
    require_wav: bool = True,
) -> list[DeleteReviewCandidateResult]:
    decisions = load_review_decisions(decisions_path)
    results: list[DeleteReviewCandidateResult] = []

    for decision in decisions.values():
        if decision.decision != "delete_candidate":
            continue

        resolved_path = resolve_review_filepath(decision.filepath, project_root=project_root)
        if require_wav and resolved_path.suffix.lower() != ".wav":
            results.append(
                _result(decision, resolved_path, "skipped_not_wav", "対象が .wav ではありません")
            )
            continue

        if not allow_outside_project and not _is_inside_project(resolved_path, project_root):
            results.append(
                _result(
                    decision,
                    resolved_path,
                    "skipped_outside_project",
                    "project root の外側なのでスキップしました",
                )
            )
            continue

        if not resolved_path.exists():
            results.append(_result(decision, resolved_path, "missing", "ファイルが存在しません"))
            continue

        if not execute:
            results.append(_result(decision, resolved_path, "would_delete"))
            continue

        try:
            resolved_path.unlink()
        except OSError as exc:
            results.append(_result(decision, resolved_path, "error", str(exc)))
        else:
            results.append(_result(decision, resolved_path, "deleted"))

    return results


def write_delete_log(
    output_path: Path | str,
    *,
    results: list[DeleteReviewCandidateResult],
    execute: bool,
    decisions_path: Path | str,
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "generated_at": utc_now_iso(),
        "execute": execute,
        "decisions_path": str(decisions_path),
        "summary": summarize_results(results),
        "results": [asdict(result) for result in results],
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def summarize_results(results: list[DeleteReviewCandidateResult]) -> dict[str, int]:
    summary: dict[str, int] = {}
    for result in results:
        summary[result.status] = summary.get(result.status, 0) + 1
    return summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Delete wav files marked as delete_candidate in review_decisions.json."
    )
    parser.add_argument(
        "--decisions",
        type=Path,
        default=PROJECT_ROOT / "evaluation_results" / "review_decisions.json",
        help="review_decisions.json path generated by review_report.html.",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="Base directory used to resolve relative filepaths.",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually delete files. Without this flag, the command only prints a dry-run plan.",
    )
    parser.add_argument(
        "--allow-outside-project",
        action="store_true",
        help="Allow deleting absolute paths outside --project-root.",
    )
    parser.add_argument(
        "--allow-non-wav",
        action="store_true",
        help="Allow deleting files that do not end in .wav.",
    )
    parser.add_argument(
        "--log-output",
        type=Path,
        default=PROJECT_ROOT / "evaluation_results" / "delete_review_candidates_log.json",
        help="JSON audit log output path.",
    )
    return parser


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    args = build_parser().parse_args()
    results = delete_review_candidates(
        args.decisions,
        project_root=args.project_root,
        execute=args.execute,
        allow_outside_project=args.allow_outside_project,
        require_wav=not args.allow_non_wav,
    )
    write_delete_log(
        args.log_output,
        results=results,
        execute=args.execute,
        decisions_path=args.decisions,
    )

    summary = summarize_results(results)
    mode = "DELETE" if args.execute else "DRY-RUN"
    logger.info("[%s] review delete candidates summary: %s", mode, summary)
    for result in results:
        logger.info("[%s] %s", result.status, result.resolved_path)
    logger.info("Audit log saved: %s", args.log_output)


if __name__ == "__main__":
    main()
