"""
Audio input level calibration utility.

This script delegates to voicerecognizer.runtime.calibration, allowing
both repository-internal calibration and standalone library use.
"""

from __future__ import annotations

from voicerecognizer.runtime.calibration import (
    ADAPTIVE_HIGH_SCALE,
    ADAPTIVE_LOW_SCALE,
    CUE_CREDIT_DELAY_SECONDS,
    CUE_SYLLABLES,
    DEFAULT_AUDIO_FILE,
    DEFAULT_CHART_FILE,
    DEFAULT_CUE_INTERVAL_SECONDS,
    DEFAULT_NOISE_SECONDS,
    DEFAULT_UTTERANCES,
    EPSILON,
    GRID_POINTS,
    MIN_DETECTION_RATIO,
    MIN_UTTERANCES,
    SPEECH_LEAD_SECONDS,
    VOICED_NOISE_RATIO,
    WARMUP_DISCARD_SECONDS,
    CalibrationResult,
    FrameLevels,
    Recording,
    Session,
    VadEvaluation,
    VadSettings,
    WindowLevels,
    analyze_recording,
    build_parser,
    build_session,
    calculate_calibration,
    calculate_frame_levels,
    calculate_trim_db,
    calculate_window_levels,
    choose_threshold,
    clamp,
    count_detections,
    countdown,
    db_ratio,
    evaluate_thresholds,
    format_config_float,
    format_evaluation,
    log_margin,
    main,
    nth_highest,
    percentile,
    print_levels,
    print_result,
    record_session,
    replace_class_defaults,
    save_audio,
    save_chart,
    simulate_vad,
    update_config_file,
    update_env_file,
)

__all__ = [
    "ADAPTIVE_HIGH_SCALE",
    "ADAPTIVE_LOW_SCALE",
    "CUE_CREDIT_DELAY_SECONDS",
    "CUE_SYLLABLES",
    "DEFAULT_AUDIO_FILE",
    "DEFAULT_CHART_FILE",
    "DEFAULT_CUE_INTERVAL_SECONDS",
    "DEFAULT_NOISE_SECONDS",
    "DEFAULT_UTTERANCES",
    "EPSILON",
    "GRID_POINTS",
    "MIN_DETECTION_RATIO",
    "MIN_UTTERANCES",
    "SPEECH_LEAD_SECONDS",
    "VOICED_NOISE_RATIO",
    "WARMUP_DISCARD_SECONDS",
    "CalibrationResult",
    "FrameLevels",
    "Recording",
    "Session",
    "VadEvaluation",
    "VadSettings",
    "WindowLevels",
    "analyze_recording",
    "build_parser",
    "build_session",
    "calculate_calibration",
    "calculate_frame_levels",
    "calculate_trim_db",
    "calculate_window_levels",
    "choose_threshold",
    "clamp",
    "count_detections",
    "countdown",
    "db_ratio",
    "evaluate_thresholds",
    "format_config_float",
    "format_evaluation",
    "log_margin",
    "main",
    "nth_highest",
    "percentile",
    "print_levels",
    "print_result",
    "record_session",
    "replace_class_defaults",
    "save_audio",
    "save_chart",
    "simulate_vad",
    "update_config_file",
    "update_env_file",
]

if __name__ == "__main__":
    main()
